spring.application.name=AIResumeAnalyzer
spring.datasource.url=jdbc:postgresql://localhost:5432/resume_analyzer
spring.datasource.username=postgres
spring.datasource.password=jayden19
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.profiles.active=local